import type { CompanySeed } from './jobs.js';

/**
 * Company watchlist seed (ADR-031): London/UK B2B SaaS companies and startups with their public
 * job-board tokens. Generated by `node scripts/detect-ats.ts --write` from the owner-reviewed
 * `tmp/watchlist-review.csv`; edit by re-running the script, not by hand. Public facts only
 * (name, domain, ATS type and board token), no personal data. `scanNow` creates any company
 * missing from Firestore and never overwrites one that exists.
 */
export const WATCHLIST_SEED: readonly CompanySeed[] = [];
